title: Iga's Blog
blog_name: Dream. Code. Impact.
subtitle: Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Developer who is seeking to improve the world

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
post_logo: posts.png
home_logo: home.png
author: Iga Kovtun
author_bio: Developer who is seeking to improve the world
author_email: "russdreamer@gmail.com"
#author_location: Citizen Of The World
#author_website_url: "www.linkedin.com/in/igor-kovtun-289420150/"
typewrite-text: The best way to predict the future is to implement it

author_work_experiences:
            - company_name: Grid Dynamics
              company_logo: griddynamics.png
              company_url: https://www.griddynamics.com
              designation: Java Developer
              description: Worked on «American Eagle» loyalty. Got Google Cloud certificate. Passed Full-Stack and DevOps courses
              visibility: true

            - company_name: Mail.Ru Group
              company_logo: mailgroup.png
              company_url: https://www.sberbank.ru
              designation: Software Engineer
              description: "«Animatic» sub-project based on Ok.Ru.<br/><b>As a Developer:</b> automated most processes: product assembly, financial calculations and reports, load sharing among workers.<br/><b>As a Project Manager:</b> recruited a team, conducted interviews, negotiated with the customer, was responsible for the deadlines and products' quality"
              visibility: true

            - company_name: Sberbank-Technology
              company_logo: sberbank.png
              company_url: https://www.sberbank.ru
              designation: Java Software Engineer
              description: Worked on a highly loaded banking service. We have developed 2 microservice modules that allow bank customers to perform some of their operations online, which reduces the workload and human operator costs.
              visibility: true
            - company_name: Stork-Group
              company_logo: stork.png
              company_url: http://stork.ru
              designation: Project manager
              description: <b>«Minutta»:</b> the application became the number one of thousands of others on the selling chart on ok.ru (the largest Russian social network). The application won Microsoft's grant to develop a mobile version of this application (10.2013). <br/><b>«AniGifts»:</b> developed a few versions of entertainment products for the Mail.ru Group, which became the top sellers on ok.ru for 5 years (2013 - 2018).
              visibility: true
            - company_name: Cronix MicroSystems
              company_logo: cronix.png
              company_url: https://cronix.ms
              designation: NodeJS developer
              description: <b>Internship</b>. Developed a web widget with facebook / twitter / google+ API which allows to share news to social nets.
              visibility: true
             

author_education_details:
              #- college_logo: mit.png
              #  college_name: MIT
              #  college_url: https://mit.org
              #  college_degree: CS Engineer
              #  description: Bachelor of Technology
              #  visibility: true

author_project_details:
            - project_title: Easy Png
              project_description: Cross-platform graphics implementation for image compression as the best multi-threaded alternative to existing ones.
              project_url: https://github.com/russdreamer/Easy-Png-Optimizer
              visibility: true
            - project_title: Computer Literacy course for IT beginners
              project_description: "Corse with tasks and all tests based on GitHub Actions. Course includes lessons: Git GUI, Bash, Git bash... in progress"
              project_url: https://github.com/russdreamer/computer_literacy
              visibility: true
            - project_title: Little thief
              project_description: In the context of the security competition, I found serious vulnerabilities in photobank service, which allow getting a product without payment. I made an application demonstrating vulnerabilities and presented ways to effectively fix it.
              project_url: https://github.com/russdreamer/Little-Thief-Android
              visibility: true
            - project_title: Friends story
              project_description: This application allows a company of friends to respond to a survey, after which the answers combine into a single storyline and render into a video story of friends.
              visibility: true
            - project_title: Survey (government project)
              project_description: Android application for social surveys as an alternative solution to an existing one. It was revealed that workers began to spend on questioning 9-10 times less time compared with the previous software.
              project_url: https://github.com/russdreamer/Survey-android-app
              visibility: true
            - project_title: Coffee Machine Counter
              project_description: "An application for ICL company to use a coffee machine: it reminds to clean the machine, charges bonuses for using it. Also, special achievements give it the game effect. Nowadays, it's in active use by the whole company."
              project_url: https://github.com/russdreamer/CoffeeMachine-Counter-Android
              visibility: true
            
# social links
github_username:  russdreamer
facebook_username: igatroll
linkedin_username: igor-kovtun-289420150
instagram_username: igatroll
telegram_username: igatroll

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# formspree (contact form)
formspree_email: russdreamer@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 #- products

# Gallery
defaults:
  -
    scope:
      #path: "gallery"
    values:
      #permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
